
---
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mn-test"
  namespace: dev
spec:
  selector:
    matchLabels:
      app: "mn-test"
  template:
    metadata:
      labels:
        app: "mn-test"
    spec:
      containers:
        - name: "mn-test"
          image: "localhost:5000/mn-test"
          ports:
            - name: http
              containerPort: 8080
            - containerPort: 5005  # Java debugger
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "mn-test"
  namespace: dev
spec:
  selector:
    app: "mn-test"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080