---
micronaut:
  application:
    name: mn-test
endpoints:
  all:
    enabled: true
    sensitive: false
---
vertx:
  mysql:
    client:
#      uri: mysql://root:password@mysql.dev.svc.cluster.local:3306/test
      port: 3306
      host: "mysql.dev.svc.cluster.local"
      database: "test"
      user: "root"
      password: "password"
      maxSize: 5
